name: CI-Pipeline

on:
  push:
    branches: [ "main", "pd_branch", "cheesyplate_branch", "vaas_branch", "solvrx_branch" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t wind-app .

      - name: Run basic health check
        # TODO
        run: docker run --rm wind-app python src/train.py