name: ML Pipeline Check

on:
  push:
    branches: [ "main", "solvrxx_branch", "pd_branch", "cheesyplate_branch", "vaas_branch" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t wind-app .

      - name: Save Docker image
        run: docker save wind-app > wind-app.tar

      - uses: actions/upload-artifact@v4
        with:
          name: docker-artifact
          path: wind-app.tar


  unit-tests:
    name: Unit tests
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: docker-artifact

      - name: Load Docker image
        run: docker load < wind-app.tar

      - name: Run unit tests
        run: docker run --rm -e PYTHONPATH=/app wind-app pytest tests/ -m "not integration"